name: Update README with recent activity

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # lets you trigger it manually from the Actions tab

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Update this repo's README with recent activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "chore: update README with recent activity"
          MAX_LINES: 5
